ALTER TABLE `TODO` ADD FOREIGN KEY ( `MemberUser` ) REFERENCES `jProject`.`Member` (
`User`
) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE `TODO` ADD FOREIGN KEY ( `MemberProject` ) REFERENCES `jProject`.`Member` (
`Project`
) ON DELETE CASCADE ON UPDATE CASCADE ;